---
# group_vars/all.yml
# Common variables
config_user: "{{ config_user_id | default(lookup('env', 'USER')) }}"
user_home: "{{ lookup('env', 'HOME') }}"
config_dir: "{{ user_home }}/.config"

# Repo URLs - override these to use your own forks
my_neovim_repo: "https://github.com/suresh-chandran-pulikkal/customized-neovim"
fish_config_repo: "https://github.com/suresh-chandran-pulikkal/fish-customised.git"
tmux_config_repo: "https://github.com/suresh-chandran-pulikkal/tmux.git"

# Debugging section
debug_vars:
  - config_user
  - user_home
  - config_dir
