---
# Variables for tmux 
tmux_user: "{{ ansible_env.USER }}"
tmux_group: "{{ ansible_env.USER }}"
tmux_conf_dir: "{{ ansible_env.HOME }}/.tmux"
user_home: "{{ ansible_env.HOME }}"

src:
  tmux_conf: "{{ user_home }}/.tmux/tmux.conf"
  tmux_conf_local: "{{ user_home }}/.tmux/local.conf"

dest:
tmux_conf: "{{ user_home }}/.tmux.conf"
tmux_conf_local: "{{ user_home }}/.tmux.conf.local"
