---
# Variables for tmux
tmux_user: "{{ ansible_env.USER }}"
tmux_group: "{{ ansible_env.USER }}"
tmux_config_dir: "{{ ansible_env.HOME }}/.config/tmux"
user_home: "{{ ansible_env.HOME }}"
tmux_config_repo: "https://github.com/suresh-chandran-pulikkal/.tmux.git"
src:
  tmux_conf: "{{ user_home }}/.tmux/.tmux.conf"
  tmux_conf_local: "{{ user_home }}/.tmux/.tmux.conf.local"

dest:
  tmux_conf: "{{ user_home }}/.tmux.conf"
  tmux_conf_local: "{{ user_home }}/.tmux.conf.local"
