---
# Variables for fish
fish_user: "{{ ansible_env.USER }}"
fish_group: "{{ ansible_env.USER }}"
fish_config_dir: "{{ ansible_env.HOME }}/.config/fish"
user_home: "{{ ansible_env.HOME }}"
fish_config_repo: "https://github.com/suresh-chandran-pulikkal/fish-customised.git"
starship_user: "{{ ansible_env.USER }}"
starship_group: "{{ ansible_env.USER }}"
src:
  starship_conf: "{{ ansible_env.HOME }}/.config/fish/.starship.toml"
dest:
  starship_conf: "{{ user_home }}/.config/starship.toml"
