base_packages:
  - git
    #  - which # which is found in debianutils package in Debian
  - debianutils
  - curl
  - wget
  - make
  - build-essential
  - unzip
  - ripgrep
  - fd-find
  - neovim
  - npm
  - python3-pip
