base_packages:
    - git
    - which
    - curl
    - wget
    - make
    - gcc
    - unzip
    - rsync
    - python3-pip
    - fd
    - neovim
    - npm 
    - ripgrep
    - stow
    - docker
    - docker-compose
    - fzf
    - eza
    - starship
    #- kubectl
    #- helm
    #- helmfile
    #- helm-diff
    #- helm-docs
    #- helmfile-fish-completion
    #- helm-schema
