---
- name: Check custom neovim repo availability
  ansible.builtin.uri:
    url: "{{ my_neovim_repo }}"
    method: GET
  register: my_neovim_repo_status
  ignore_errors: true

- name: Deploy custom neovim configurations from git repo
  ansible.builtin.git:
    repo: "{{ my_neovim_repo }}"
    dest: "{{ nvim_config_dir }}/nvim"
    version: main
    update: true
    force: true


# 29-May-2025
# Below is the old code for the custom config
# It is kept here for reference
#
# - name: Ensures custom config directory exists
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: directory
#     owner: "{{ nvim_user }}"
#     group: "{{ nvim_user }}"
#     mode: '0755'
#   loop:
#     - "{{ configs.dest }}"
#     - "{{ plugins.dest }}"
#
# - name: Check if config source directory exists
#   stat:
#     path: "{{ configs.src }}"
#   register: config_src_status
#   changed_when: false
#
# - name: Sync config custom files (if any exists)
#   synchronize:
#     src: "{{ configs.src }}/"
#     dest: "{{ configs.dest }}/"
#     recursive: yes
#     owner: yes
#   when: config_src_status.stat.exists and config_src_status.stat.isdir
#
# - name: Check if plugins source directory exists
#   stat:
#     path: "{{ plugins.src }}"
#   register: plugins_src_status
#   changed_when: false
#
# - name: Deploy plugins custom files (if any exists)
#   synchronize:
#     src: "{{ plugins.src }}"
#     dest: "{{ plugins.dest }}"
#     recursive: yes
#     owner: yes
#   when: plugins_src_status.stat.exists and plugins_src_status.stat.isdir
