---
- name: Deploy tmux config files from git repo
  ansible.builtin.git:
    repo: "{{ tmux_config_repo }}"
    dest: "{{ tmux_config_dir }}"
    force: true
  tags: [config]

- name: Create symlink for tmux config files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    owner: "{{ tmux_user }}"
    group: "{{ tmux_group }}"
  loop:
    - { src: "{{ src.tmux_conf }}", dest: "{{ dest.tmux_conf }}" }
    - { src: "{{ src.tmux_conf_local }}", dest: "{{ dest.tmux_conf_local }}" }
  tags: [config]
