# roles/setup-tmux/tasks/main.yml
- name: Install tmux using zypper
  ansible.builtin.zypper:
    name: tmux
    state: present
  become: true

- name: Validate tmux installation
  ansible.builtin.command: /usr/bin/tmux -V
  register: tmux_version
  changed_when: false
  ignore_errors: yes

- name: Fail if tmux installation failed
  ansible.builtin.fail:
    msg: >
      tmux not installed. Exit code: {{ tmux_version.rc }},
      Error: {{ tmux_version.stderr }}
  when: tmux_version.rc != 0
