---
- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  become: true
  tags: [install]

- name: Validate tmux installation
  ansible.builtin.command: /usr/bin/tmux -V
  register: tmux_version
  changed_when: false
  ignore_errors: true
  tags: [install]

- name: Fail if tmux installation failed
  ansible.builtin.fail:
    msg: >
      tmux not installed. Exit code: {{ tmux_version.rc }},
      Error: {{ tmux_version.stderr }}
  when: tmux_version.rc != 0
  tags: [install]
