---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
  tags: install

- name: Include configuration tasks
  ansible.builtin.include_tasks: config.yml
  tags: config

- name: Include validation tasks
  ansible.builtin.include_tasks: validate.yml
  tags: validate
