---
- name: Install and validate fish
  become: true
  tasks:
    - name: Install fish
      ansible.builtin.package:
        name: fish
        state: present

    - name: Validate fish installation
      ansible.builtin.command: fish --version
      register: fish_version
      changed_when: false

    - name: Fail if fish is not installed
      ansible.builtin.fail:
        msg: "fish is not installed"
      when: fish_version.rc != 0
