---
- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present
  become: true
  tags: [install]

- name: Validate fish installation
  ansible.builtin.shell: |
    command -v fish && /usr/bin/fish --version
  args:
    executable: /bin/bash
  register: fish_version
  changed_when: false
  ignore_errors: true
  tags: [install]

- name: Fail if fish is not installed
  ansible.builtin.fail:
    msg: >
      Failed to install fish.
        Error output: {{ fish_version.stderr }}
  when: fish_version.rc != 0
  tags: [install]
