- name: Install fish
  ansible.builtin.command: zypper -n install fish
  # zypper:
  #   name: fish
  #   state: present
  #   force: yes
  register: install_result
  become: true

- name: Validate fish installation
  ansible.builtin.shell: |
    command -v fish && /usr/bin/fish --version
  args:
    executable: /bin/bash
  register: fish_version
  changed_when: false
  ignore_errors: yes

- name: Fail if fish is not installed
  ansible.builtin.fail:
    msg: >
      Failed to install fish. Zypper error:
        Return code: {{ install_result.rc }}
        Output: {{ install_result.stdout }}
        Error output: {{ fish_version.stderr }}
  when: fish_version.rc != 0 or install_result is failed
