---
# Neovim variables
# Direct definitions without circular references
nvim_user: "{{ lookup('env', 'USER') }}"
nvim_home: "{{ lookup('env', 'HOME') }}"
nvim_config_dir: "{{ nvim_home }}/.config"

lazyvim_repo: "https://github.com/LazyVim/starter"
# Custom config files paths 
configs:
  src: "{{ playbook_dir }}/../files/neovim/config/custom/"
  dest: "{{ nvim_config_dir }}/nvim/lua/config/custom/"
# Custom plugins files paths
plugins:
  src: "{{ playbook_dir }}/../files/neovim/plugins/custom/"
  dest: "{{ nvim_config_dir }}/nvim/lua/plugins/custom/"

# Debugging section
#debug_vars:
#  - config_user
