---
- name: Configure multi-distro workstation
  hosts: localhost
  connection: local
  become: yes
  tasks:
  -name: Include distro-specific variables
  include_vars: "{{ansible_distribution|lower}}".yml
when: ansible_distribution is defined
ignore_errors: yes

roles:
- base_packages
- neovim
- tmux
- shell
- dotfiles
- ssh
