---
- name: Configure workstation
  hosts: workstations
  gather_facts: true
  roles:
    - role: base_packages
      tags: base_packages
    - role: neovim
      tags: neovim
    - role: setup-tmux
      tags: setup-tmux
    - role: setup-fish
      tags: setup-fish
