---
- name: Check if nvim config exists
  stat:
    path: "{{ config_dir }}/nvim"
  register: nvim_config
  changed_when: false
  when: backup_nvim_config | default(true) | bool

- name: Backup existing nvim config if enabled and exists
  block:
    - name: Create backup directory
      file:
        path: "{{ config_dir }}/nvim.bak"
        state: directory
        mode: '0755'
    
    - name: Copy existing config to backup
      become: true
      synchronize:
        src: "{{ config_dir }}/nvim/"
        dest: "{{ config_dir }}/nvim.bak/"
        recursive: yes
        owner: yes
    - name: remove existing nvim directory
      file:
        path: "{{ config_dir }}/nvim/"
        state: absent
  when:
    - backup_nvim_config | default(true) | bool
    - nvim_config.stat.exists
  rescue:
    - name: Backup failed warning
      debug:
        msg: "NVim config backup failed, continuing with installation"
      changed_when: false

- name: Install LazyVim starter
  git:
    repo: "https://github.com/LazyVim/starter"
    dest: "{{ config_dir }}/nvim"
    version: main
    update: yes
    force: yes
