---
- name: Update apt cache
  apt:
      update_cache: yes
      cache_valid_time: 3600
      name:
        - git
        - curl
        - fzf
        - python3-pip
        - build-essential
        - pssh
        - openssh-client
        - unzip
      state: present
